num_workers: 16
max_sequence_length: 512

sequence_length: 128
# ---------------------------------- Splits ---------------------------------- #
train: 0.8
test: 0.1
val: 0.1 
seed: 42

# ---------------------------- Spectrogram configs --------------------------- #
preprocess_method: 'logmel' # 'logmel' or 'cqt'
sr: 22050 # sample rate
n_fft: 2048 # number of samples used for each fourier transform
hop_length: 512 # hop_length. The number of samples between successive frames is n_fft - hope_length
n_mels: 128 # number of mel bands to generate


# List of dataset directories
data_dirs:
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2004
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2006
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2008
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2009
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2011
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2013
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2014
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2015
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2017
  - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2018

audio_file_extension: '.wav'
output_dir: '/work3/s214629/preprocessed_128_const'  # Preprocessed data will be saved to output_dir/spectrograms/ and output_dir/labels/