# ---------------------------------- Splits ---------------------------------- #
train: 0.85 # 0.8
test: 0.05 # 0.1
val: 0.1 # 0.1
seed: 42
dataset: MuseScore

# ---------------------------- Spectrogram configs --------------------------- #
max_sequence_length: 512
preprocess_method: 'logmel' # 'logmel' or 'cqt'
h_bars: 6 # hyperparameter: number of bars to slice the audio into
sr: 22050 # sample rate
n_fft: 2048 # number of samples used for each fourier transform
hop_length: 512 # hop_length. The number of samples between successive frames is n_fft - hope_length
n_mels: 128 # number of mel bands to generate

# -------------------------------- Directories ------------------------------- #
# List of dataset directories
data_dirs:
  - "/work3/s214629/data/bachelor_musescore"

audio_file_extension: ['.wav', '.mp3']
score_file_extensions: ['xml', 'mxl']
midi_file_extensions: ['mid', 'midi']
output_dir: '/work3/s214629/preprocessed_data/05-05-24' # '/work3/s214629/preprocessed_data_best'  # Preprocessed data will be saved to output_dir/spectrograms/ and output_dir/labels/

# ------------------------------ Miscellaneous ------------------------------ #
num_workers: 8