num_workers: 20
max_sequence_length: 512

sequence_length: 128
# ---------------------------------- Splits ---------------------------------- #
train: 0.8
test: 0.05
val: 0.15
seed: 42

# ---------------------------- Spectrogram configs --------------------------- #
preprocess_method: 'logmel' # 'logmel' or 'cqt'
sr: 22050 # sample rate
n_fft: 2048 # number of samples used for each fourier transform
hop_length: 512 # hop_length. The number of samples between successive frames is n_fft - hope_length
n_mels: 128 # number of mel bands to generate


# List of dataset directories
data_dirs:
  - /work3/s214629/data/asap_generated
  - /work3/s214629/data/bachelor_musescore_generated
  - /work3/s214629/data/hausmusik_generated
  - /work3/s214629/data/folkopedia_generated
  - /work3/s214629/data/ambrose-piano-tab_generated

augmented_dataset: null #/work3/s214629/data/augmented_data_generated


audio_file_extensions: 
  - '.wav'
  - '.mp3'

output_dir: '/work3/s214629/preprocessed_data/13-06-2024_TS_ambr'  # Preprocessed data will be saved to output_dir/spectrograms/ and output_dir/labels/