# ---------------------------------- Splits ---------------------------------- #
train: 0.25 # 0.8
test: 0.25 # 0.1
val: 0.50 # 0.1
seed: 42
dataset: MuseScore

# ---------------------------- Spectrogram configs --------------------------- #
max_sequence_length: 512
preprocess_method: 'logmel' # 'logmel' or 'cqt'
h_bars: 3 # hyperparameter: number of bars to slice the audio into
sr: 22050 # sample rate
n_fft: 2048 # number of samples used for each fourier transform
hop_length: 512 # hop_length. The number of samples between successive frames is n_fft - hope_length
n_mels: 128 # number of mel bands to generate

# -------------------------------- Directories ------------------------------- #
# List of dataset directories
data_dirs:
  - "/Users/helenakeitum/Desktop/test_data"
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2004
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2006
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2008
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2009
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2011
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2013
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2014
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2015
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2017
  # - /work3/s214629/maestro-v3.0.0/maestro-v3.0.0/2018

audio_file_extension: ['.wav', '.mp3']
score_file_extensions: ['xml', 'mxl']
midi_file_extensions: ['mid', 'midi']
output_dir: 'preprocessed_data_best' # '/work3/s214629/preprocessed_data_best'  # Preprocessed data will be saved to output_dir/spectrograms/ and output_dir/labels/

# ------------------------------ Miscellaneous ------------------------------ #
num_workers: 1 # 16