# ------------------------------ Miscellaneous ------------------------------ #
num_workers: 20
max_sequence_length: 512
sequence_length: 128

# ---------------------------------- Splits ---------------------------------- #
train: 0.8
test: 0.1
val: 0.1
seed: 42
dataset: MuseScore

# ---------------------------- Spectrogram configs --------------------------- #
preprocess_method: 'stft'   # 'logmel' or 'cqt'
min_beats: 8 # hyperparameter: minimum number of beats to slice the audio into
max_beats: 28 # hyperparameter: maximum number of beats to slice the audio into
sr: 22050 # sample rate
n_fft: 2048 # number of samples used for each fourier transform
hop_length: 512 # hop_length. The number of samples between successive frames is n_fft - hope_length
n_mels: 1025 # number of mel bands to generate

# -------------------------------- Model ------------------------------- #
model: 'BeatTrack' #TimeShift or BeatTrack

# -------------------------------- Directories ------------------------------- #
# List of dataset directories
data_dirs:
  - /work3/s214629/data/asap_generated
  - /work3/s214629/data/Lieder_generated
  - /work3/s214629/data/music21_generated

augmented_dataset: /work3/s214629/data/augmented__generated
augmented_dataset_percentage_to_use: 1

audio_file_extensions:
  - '.wav'
  - '.mp3'

score_file_extensions:
  - '.xml'
  - '.mxl'
  - '.musicxml'

midi_file_extensions:
  - '.mid'
  - '.midi'

output_dir: '/work3/s214629/data/final_prprc_data/logmel'                     # Preprocessed data will be saved to output_dir/spectrograms/ and output_dir/labels/
output_base_dir: '/work3/s214629/data/final_prprc_data'
output_specific_dir: 'logmel'
