run_folder_paths: # In case training of one model spans multiple runs. Put the folders in order!!
  - C:\University\batchelor_amt\runs\TS_logmel_big

# Ideally would be the same as the last run folder path
output_dir: C:\University\batchelor_amt\runs\TS_logmel_big 

# We could add a merge runs option here

