
# ------------------------------- Train configs ------------------------------ #
num_epochs: 200
batch_size: 8
lr: 0.00001
run_save_path: '/work3/s214629/runs/04-06-24_00001' # This will create a folder with run_1/losses with train_losses and val_losses as well as run_1/models
data_dir: '/work3/s214629/preprocessed_data/04-06-24_m-28' # This is the path to the preprocessed data directory
seed: 42
# -------------------------- Model specific configs -------------------------- #
n_mel_bins: 128
d_model: 512
num_heads: 8
num_layers: 6
d_ff: 2048
max_seq_length: 4096 # 1024 # doesn't really matter, can be set to whatever as long as its larger than the longest sequence - it's a pteprocess step for PE
dropout: 0.1
