special_tokens:
  - PAD # Only used in dataloader
  - SOS
  - EOS
  - ET

event_types: 
  pitch: [0,127]
  offset_onset: [0, 1]  # 1 is onset, 0 is offset
  beat: [1, 160] # The chronological order of 32 notes and 8 tuplets for 4 bars

subdivision: 0.125 # 32nd note
  
