special_tokens:
  - PAD # Only used in dataloader
  - SOS
  - EOS
  - ET
  - downbeat

event_types: 
  pitch: [0, 127] # Note that the -2 and -1 tokens are helper tokens to mark tempo and downbeats. They do not represent a pitch in of themselves
  offset_onset: [0, 1]  # 1 is onset, 0 is offset
  time_shift: [1, 1600]
  beat: None #  Dynamically set inside vocabularies.py with the assumption of 32 notes and 16 tuplets (48 total)
  tempo: [10, 300] # BPM

# NOTE IF USING SOMETHING ELSE THAN 48, THEN CHANGE IT MANUALLY INSIDE define_vocabulary() in vocabularies.py

subdivision: 0.125 # 32nd note
tuplet_subdivision: 1/6 # 16th note triplet - Is wrapped in a Fraction class in the code
  

