special_tokens:
  - PAD # Only used in dataloader 
  - EOS
  - ET

event_types: 
  pitch: [0,127]
  offset_onset: [0, 1]  # 1 is onset, 0 is offset
  time_shift: [1, 3000] # TODO: change this to be more flexible, for now it's 1 idx is equal 10 ms



  
